# This is a basic workflow to help you get started with Actions

name: Deploy (GitHub -> DockerHub -> Kubernetes)

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: okkdev/kummerbot:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: [ build ]
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to cluster
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.KUBE_CONFIG_DATA }}
          args: set image -n apps --record deployment/kummerbot-deployment kummerbot=okkdev/kummerbot:latest
      - name: Verify deployment
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.KUBE_CONFIG_DATA }}
          args: '"rollout status -n apps deployment/kummerbot-deployment"'
